/** Cliente de administración de Access para el BFF de una app (Next, node, edge). Reexporta `createAccessAdmin` de `@customyai/access`: `@customyai/sdk/admin`. */
export { accessScopeHeaders, createAccessAdmin } from "@customyai/access";
export type {
    AccessAdmin,
    AccessAdminCallOptions,
    AccessAdminMe,
    AccessAdminOptions,
    AccessAdminResponse,
    AccessAdminScope,
    AccessDirectoryMember,
    AccessGovernanceToken,
    AccessSessionPayload,
    AccessCommercial,
    AccessCommercialCallOptions,
    AgencyPlanInput,
    CeilingViolation,
    CommercialController,
    CommercialPayer,
    CommercialRelationship,
    CommercialRelationshipVersion,
    CommercialTerms,
    EntitlementExplanation,
    ExplainInput,
    ExplainStep,
    ExplainStepCode,
    PlanSummary,
    PlanValidation,
    ResolveSettlementInput,
    SetCommercialRelationshipInput,
    SettlementLeg,
    SettlementListPriceSource,
    SettlementMargin,
    SettlementMode,
    SettlementResult,
    SettlementStep,
    SettlementStepCode,
    SubscriptionAccessMode,
    SubscriptionAccessPolicyEntry,
    SubscriptionPolicyState,
    VisiblePlans,
} from "@customyai/access";
export { discoverApplication, clearApplicationCache, type CustomyApplication, type DiscoverApplicationOptions } from "@customyai/core";
